import {parseProductionPlan, type ProductionPlan} from '../src/production/production-plan';

export const makeProductionPlan = (): ProductionPlan => parseProductionPlan({
  schemaVersion: 3,
  projectId: 'offline-football-demo',
  metadata: {title: '足球射门：方向与接触', locale: 'zh-CN'},
  networkPolicy: 'offline-only',
  requiredCapabilities: [
    'local-f5-tts',
    'local-i2v',
    'local-video-matting',
    'deterministic-ballistics',
    'remotion-render',
    'ffmpeg',
    'sidecar-srt',
  ],
  delivery: {
    raster: {width: 1080, height: 1920, pixelAspectRatio: 1},
    timeline: {fps: 30, durationFrames: 101},
    video: {path: 'generated/final/video.mp4', codec: 'h264', pixelFormat: 'yuv420p'},
    audio: {
      path: 'generated/audio/narration.wav',
      sourceFormat: 'wav',
      muxCodec: 'aac',
      muxSampleRate: 48000,
    },
    subtitles: {path: 'generated/final/video.srt', format: 'srt', burnIn: false},
    bgm: null,
  },
  narration: {
    engine: 'f5-tts-local',
    language: 'zh-CN',
    referenceAudioPath: 'assets/voices/narrator.wav',
    referenceText: '这是经过授权的本地声音参考。',
    speed: 1,
    segments: [{
      segmentId: 'narration-kick',
      shotId: 'kick-01',
      text: '支撑脚落地，身体朝向球门，右脚正面完成一次射门。',
      outputPath: 'generated/audio/kick-01.wav',
    }],
    mergedAudioPath: 'generated/audio/narration.wav',
  },
  shots: [{
    kind: 'generated-performance',
    shotId: 'kick-01',
    deliveryTimeline: {startFrame: 0, durationFrames: 101},
    generation: {
      engine: 'wangp-local-i2v',
      conditioning: {
        mode: 'start-only',
        startKeyframePath: 'assets/shots/kick-01/performance-start.png',
      },
      preset: {
        id: 'portrait-i2v-quality',
        quality: 'quality',
        conditioning: 'start-only',
        motionStrength: 0.82,
      },
      raster: {width: 480, height: 832},
      timeline: {fps: 24, frameCount: 81},
      conformToDelivery: {
        spatialFit: 'cover',
        focalPoint: {x: 0.5, y: 0.56},
        temporalFit: 'preserve-duration',
      },
      candidateSeeds: [42, 314159],
    },
    hybridMotion: {
      actor: {
        id: 'kicker',
        supportingActorIds: ['goalkeeper'],
        action: 'one right-foot instep strike and balanced follow-through',
        prompt: 'Locked camera. The kicker plants the left foot, swings the right leg once, and follows through toward the goal.',
        negativePrompt: 'ball, camera movement, sliding feet, extra limbs, reversed body direction',
        generatedCamera: 'locked',
        excludedCausalPropIds: ['ball'],
      },
      world: {
        subjectId: 'kicker',
        targetId: 'goal',
        generatedObjectIds: [],
        supportSurfaceId: 'pitch',
        actionAxis: {from: {x: 0.48, y: 0.82}, to: {x: 0.51, y: 0.2}},
        milestones: [
          {id: 'setup', kind: 'setup', frame: 0},
          {id: 'plant', kind: 'plant', frame: 34},
          {id: 'foot-contact', kind: 'contact', frame: 50},
          {id: 'follow', kind: 'follow-through', frame: 71},
          {id: 'end', kind: 'end', frame: 100},
        ],
        constraints: {
          facing: [{
            id: 'face-goal',
            actorId: 'kicker',
            towardTargetId: 'goal',
            bodyAxis: 'torso',
            fromMilestoneId: 'setup',
            throughMilestoneId: 'follow',
            maxDeviationDegrees: 28,
          }],
          support: [{
            id: 'plant-left-foot',
            actorId: 'kicker',
            bodyPart: 'left-foot',
            surfaceId: 'pitch',
            mode: 'planted',
            fromMilestoneId: 'plant',
            throughMilestoneId: 'foot-contact',
            maxSlipPixels: 10,
          }],
          contact: [{
            id: 'right-foot-ball-contact',
            actorId: 'kicker',
            bodyPart: 'right-foot',
            target: {owner: 'deterministic-interaction', propId: 'ball'},
            milestoneId: 'foot-contact',
            kind: 'strike',
            toleranceFrames: 1,
          }],
        },
      },
      deterministicProps: [{
        propId: 'ball',
        assetPath: 'assets/shots/kick-01/ball.png',
        renderSize: {width: 64, height: 64},
        trigger: {milestoneId: 'foot-contact', kind: 'contact'},
        transform: {x: 522, y: 1556, scaleX: 1, scaleY: 1, rotationDegrees: 0},
        motion: {
          kind: 'ballistic',
          contactFrame: 50,
          flightFrames: 50,
          targetX: 554,
          targetY: 429,
          targetScale: 0.18,
          curveX: 40,
          spinDegrees: 540,
        },
      }],
      editorialCamera: {owner: 'editorial-camera', operation: 'push', strength: 0.16},
    },
    occlusion: {
      mode: 'local-matte',
      requirement: 'required',
      subjectId: 'kicker',
      engine: 'local-video-matting',
      outputDirectory: 'generated/mattes/kick-01',
      outputFormat: 'webm-alpha',
      foregroundAssetPath: 'assets/shots/kick-01/foreground-net.png',
      featherPixels: 2,
    },
  }],
});
